---
- hosts: group1
  sudo: yes
  vars:
    - ssh_permit_root: "yes"
    - ssh_keys:
      - mkskill
      - beli
      - beli@cgrx9
  roles:
    - role: common

- hosts: group1:&hypervisors
  sudo: yes
  roles:
    - role: kvm

- hosts: group1:&storage
  sudo: yes
  roles:
    - role: glusterfs
